name: Prod CI/CD

on:
  push:
    branches: [prod]

permissions:
  contents: read

jobs:
  build:
    runs-on:
      group: Default
      labels: [self-hosted, dev]
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
        env:
          VITE_DOMAIN: ${{ secrets.VITE_DOMAIN_PROD }}

      - name: Copy to Prod Server
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.PROD_USER_NAME }}
          host: ${{ secrets.PROD_SERVER }}
          key: ${{ secrets.PROD_PEM_KEY }}
          source: './dist'
          target: '~/'
